### ISSUE TITLE
Migrate to logger version 2

### ISSUE THREAD

**Issue by lagivan** [icapps/flutter-icapps-architecture#111]
Current dependency is `logger: ^1.4.0`. However, many packages have already migrated to logger v2, for example, flutter_map. To resolve conflicts could you please migrate to the latest logger?

Now the following error occurs:
```
Because icapps_architecture >=2.1.0 depends on logger ^1.4.0 and flutter_map >=6.0.0 depends on logger ^2.0.1, icapps_architecture >=2.1.0 is incompatible with flutter_map >=6.0.0.
```

**Comment by ikbendewilliam** [comment]
Fixed in icapps_architecture 2.1.5 😄
