### ISSUE TITLE
BaseThemeProviderWidget does not pass named super.key parameter

### ISSUE THREAD

**Issue by lagivan** [icapps/flutter-icapps-architecture#118]
The linting rule https://dart.dev/tools/linter-rules/use_key_in_widget_constructors enforces adding super.key parameter in public widgets. However, when extending BaseThemeProviderWidget it's not possible to pass the key via the constructor as BaseThemeProviderWidget does not follow this practice:

```
  const BaseThemeProviderWidget({
    this.childBuilderTheme,
    this.childBuilderLocalization,
    this.childBuilder,
  });
```

Instead it could be this:

```
  const BaseThemeProviderWidget({
    this.childBuilderTheme,
    this.childBuilderLocalization,
    this.childBuilder,
    super.key,
  });
```

This would allow adding super.key when creating a project specific DataProviderWidget.

**Comment by ikbendewilliam** [comment]
@lagivan Thank you for your PR, I just released it in version 2.2.2
