### ISSUE TITLE
Proxy of device is ignored.

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-icapps-architecture#48]
This is a known issue in flutter: https://github.com/flutter/flutter/issues/26359

This can be fixed with the following plugin:
https://pub.dev/packages/osproxysetting

**Comment by ikbendewilliam** [comment]
It would seem that there is now something for this in io, other libraries have not been migrated to null safety...
```
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client) async {
      client.findProxy = HttpClient.findProxyFromEnvironment;
    };
```

**Comment by NicolaVerbeeck** [comment]
This feels like something for the template project, not the lib

**Comment by vanlooverenkoen** [comment]
Yes indeed

**Comment by vanlooverenkoen** [comment]
Won't fix in this lib
